services:
  docs:
    image: developer_landing_local_docs
    container_name: developer_landing_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./developer_landing:/app/developer_landing:z
    ports:
      - '9000:9000'
    command: /start-docs
