# Generated by Django 6.0.7 on 2026-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('request_type', models.CharField(blank=True, choices=[('lead', 'Lead'), ('question', 'Question'), ('bug', 'Bug'), ('partnership', 'Partnership'), ('other', 'Other')], default='', max_length=32)),
                ('ai_reply', models.TextField(blank=True, default='')),
                ('ai_available', models.BooleanField(default=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'Contact requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
